package com.lezi.babylog.feature.export

/** Fixed diagnostic vocabulary; never contains request data, paths, or IPC tokens. */
internal enum class ExportMilestone {
    BIND_REQUESTED, BIND_CONNECTED, HELLO_SENT, HELLO_RECEIVED,
    READY_SENT, READY_RECEIVED, RENDER_SENT, RENDER_RECEIVED,
    DECODE_STARTED, DECODE_FINISHED, RENDER_STARTED, RENDER_FINISHED,
    COMPLETE_RECEIVED, FAILED_RECEIVED, CANCELLED, SERVICE_CREATED, SERVICE_ABORTING,
    PDF_DOCUMENT_CREATED, PDF_TEXT_STARTED, PDF_TEXT_FINISHED,
    PHOTO_DECODE_STARTED, PHOTO_DECODE_FINISHED, PDF_PHOTO_STARTED, PDF_PHOTO_FINISHED,
    PDF_WRITE_STARTED, PDF_WRITE_FINISHED,
}
